name: label_field
description: "A widget to show the label text above the field widget."
version: 1.0.0
repository: https://github.com/RightBrainPro/label_field
issue_tracker: https://github.com/RightBrainPro/label_field/issues

publish_to: https://pub.rightbrain.pro/

environment:
  sdk: ^3.10.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
